# Generated by Django 3.1.4 on 2021-02-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
