# Generated by Django 3.1.4 on 2021-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210216_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_summary',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
