# Generated by Django 3.1.4 on 2021-02-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='theory',
        ),
    ]
