# Generated by Django 3.1.4 on 2021-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_remove_lesson_theory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
