# Generated by Django 3.1.4 on 2021-03-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20210311_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.lesson'),
        ),
    ]
