# Generated by Django 3.1.4 on 2021-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20210311_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.CharField(max_length=100),
        ),
    ]
