# Generated by Django 3.1.4 on 2021-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20210311_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='mainsite.Lesson'),
        ),
    ]
