# Generated by Django 3.1.4 on 2021-03-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_user_completed_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('all', 'All'), ('cpp17', 'C++'), ('python3', 'Python 3'), ('nodejs', 'NodeJS'), ('java', 'Java')], default='all', max_length=10),
        ),
    ]
