# Generated by Django 3.1.4 on 2021-05-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('all', 'all'), ('cpp17', 'cpp17'), ('python3', 'python3'), ('nodejs', 'nodejs'), ('java', 'java')], default='all', max_length=10),
        ),
    ]
